Importei a biblioteca Pandas

In [ ]:
import pandas as pd

# **Dados de Junho**ðŸ“…

In [ ]:
junho = pd.read_csv('https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/shpc/dsan/2021/2021-06-gasolina-etanol.csv', sep=';')
junho.head()

  RegiÃ£o - Sigla Estado - Sigla  ... Unidade de Medida                      Bandeira
0              N             AC  ...        R$ / litro  PETROBRAS DISTRIBUIDORA S.A.
1              N             AC  ...        R$ / litro  PETROBRAS DISTRIBUIDORA S.A.
2              N             AC  ...        R$ / litro  PETROBRAS DISTRIBUIDORA S.A.
3              N             AC  ...        R$ / litro  PETROBRAS DISTRIBUIDORA S.A.
4              N             AC  ...        R$ / litro                        BRANCA

[5 rows x 16 columns]

In [ ]:
junho['Valor de Venda'] = junho['Valor de Venda'].apply(lambda x:x.replace(',', '.')).astype(float)#transformando o campo valor de venda pra float
del junho['Valor de Compra'] #excluindo a coluna vazia

# **Dados de JulhoðŸ“…**

In [ ]:
julho = pd.read_csv('https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/shpc/dsan/2021/2021-07-gasolina-etanol.csv', sep=';')
julho

      RegiÃ£o - Sigla  ...                      Bandeira
0                 NE  ...                      IPIRANGA
1                 NE  ...                      IPIRANGA
2                 NE  ...                      IPIRANGA
3                 NE  ...  PETROBRAS DISTRIBUIDORA S.A.
4                 NE  ...  PETROBRAS DISTRIBUIDORA S.A.
...              ...  ...                           ...
47844             SE  ...                        BRANCA
47845             SE  ...                        BRANCA
47846             SE  ...                        BRANCA
47847             SE  ...                    RIO BRANCO
47848             SE  ...                    RIO BRANCO

[47849 rows x 16 columns]

In [ ]:
julho['Valor de Venda'] = julho['Valor de Venda'].apply(lambda x:x.replace(',', '.')).astype(float)#transformando o campo valor de venda pra float
del julho['Valor de Compra'] #excluindo a coluna vazia

Exibi os dois links acima e depois os juntei em um Ãºnico dataframe

In [ ]:
dataframe_JyJ = pd.concat([junho, julho],ignore_index=True)
dataframe_JyJ

      RegiÃ£o - Sigla  ...                      Bandeira
0                  N  ...  PETROBRAS DISTRIBUIDORA S.A.
1                  N  ...  PETROBRAS DISTRIBUIDORA S.A.
2                  N  ...  PETROBRAS DISTRIBUIDORA S.A.
3                  N  ...  PETROBRAS DISTRIBUIDORA S.A.
4                  N  ...                        BRANCA
...              ...  ...                           ...
97581             SE  ...                        BRANCA
97582             SE  ...                        BRANCA
97583             SE  ...                        BRANCA
97584             SE  ...                    RIO BRANCO
97585             SE  ...                    RIO BRANCO

[97586 rows x 16 columns]

# **3 - Quais os 5 estados com preÃ§o mÃ©dio de gasolina e etanol mais caros?**

In [ ]:
dataframe_JyJ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97586 entries, 0 to 97585
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RegiÃ£o - Sigla     97586 non-null  object
 1   Estado - Sigla     97586 non-null  object
 2   MunicÃ­pio          97586 non-null  object
 3   Revenda            97586 non-null  object
 4   CNPJ da Revenda    97586 non-null  object
 5   Nome da Rua        97586 non-null  object
 6   NÃºmero Rua         97529 non-null  object
 7   Complemento        19711 non-null  object
 8   Bairro             97327 non-null  object
 9   Cep                97586 non-null  object
 10  Produto            97586 non-null  object
 11  Data da Coleta     97586 non-null  object
 12  Valor de Venda     97586 non-null  object
 13  Valor de Compra    0 non-null      float64
 14  Unidade de Medida  97586 non-null  object
 15  Bandeira           97586 non-null  object
dtypes: float64(1), object(15)
memory usage: 11.9+ MB

In [ ]:
# dataframe_JyJ['Valor de Venda']=dataframe_JyJ['Valor de Venda'].str.replace(',','.') 
dataframe_JyJ['Valor de Venda']=dataframe_JyJ['Valor de Venda'].astype(float)
etanol = dataframe_JyJ[dataframe_JyJ['Produto']=='ETANOL'].groupby(['Estado - Sigla', 'Produto']).agg( {"Valor de Venda":"mean"}).round(2).sort_values('Valor de Venda',ascending=False).head(5)
gasolina= dataframe_JyJ[dataframe_JyJ['Produto'].str.contains('GASOLINA$')].groupby(['Estado - Sigla', 'Produto']).agg( {"Valor de Venda":"mean"}).round(2).sort_values('Valor de Venda',ascending=False).head(5)
# gasolina_adt= dataframe_JyJ[dataframe_JyJ['Produto'].str.contains('GASOLINA AD')].groupby(['Estado - Sigla', 'Produto']).agg( {"Valor de Venda":"mean"}).round(2).sort_values('Valor de Venda',ascending=False).head(5)

cinco_estados = pd.concat([etanol, gasolina], join="outer")
cinco_estados

                         Valor de Venda
Estado - Sigla Produto
RS             ETANOL              5.81
AC             ETANOL              5.54
RN             ETANOL              5.52
PA             ETANOL              5.33
AP             ETANOL              5.31
AC             GASOLINA            6.44
RJ             GASOLINA            6.30
RN             GASOLINA            6.15
PI             GASOLINA            6.11
GO             GASOLINA            6.04

#ConcluÃ­mos que os cinco estados com o preÃ§o mÃ©dio de gasolina e etanol mais caros sÃ£o, para Etanol: 


1. **Rio Grande do Sul**
2. **Acre**
3. **Rio Grande do Norte**
4. **ParÃ¡**
5. AmapÃ¡.


#Para Gasolina, foram os seguintes estados:


1.   **Acre**
2.   **Rio de Janeiro**
3.   **Rio Grande do Norte**
4.   **PiauÃ­**
5.   **GoiÃ¡s**

## **4 - Qual o preÃ§o mÃ©dio da Gasolina e do Etanol por estado?**

In [ ]:
mediaestado=dataframe_JyJ.groupby(['Produto', 'Estado - Sigla'])['Valor de Venda'].mean().round(2)
mediaestado.unstack()[:2]

Estado - Sigla    AC    AL    AM    AP    BA  ...    RS    SC    SE    SP    TO
Produto                                       ...
ETANOL          5.54  5.19  4.45  5.31  4.94  ...  5.81  5.02  5.05  4.14  5.13
GASOLINA        6.44  5.96  5.56  4.99  5.96  ...  6.02  5.49  5.69  5.46  5.93

[2 rows x 27 columns]

#Ao analisar, notamos que o **Acre** possui a maior mÃ©dia de preÃ§o para **Gasolina**, no valor de **6,44** e o estado do **Rio Grande do Sul**, possui a maior mÃ©dia para **Etanol** no valor de **5,81**